// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuz4yA4LOsa3ANHndAmgirF1d8QaJ2z6o',
    appId: '1:661690890987:web:df838e2925dc2a707d5cae',
    messagingSenderId: '661690890987',
    projectId: 'privateapp-hamasur',
    authDomain: 'privateapp-hamasur.firebaseapp.com',
    storageBucket: 'privateapp-hamasur.appspot.com',
    measurementId: 'G-L4MT4JP8TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCRejpGsGPUk9WNfNGmasu_WubF3QTnFk',
    appId: '1:661690890987:android:fe043907d2158c4e7d5cae',
    messagingSenderId: '661690890987',
    projectId: 'privateapp-hamasur',
    storageBucket: 'privateapp-hamasur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP65QI-76Lk904KUkjnuCce9KPhySNaLs',
    appId: '1:661690890987:ios:91698947b740cc0a7d5cae',
    messagingSenderId: '661690890987',
    projectId: 'privateapp-hamasur',
    storageBucket: 'privateapp-hamasur.appspot.com',
    iosClientId: '661690890987-ut13rgboe23s2if40kvtvrh2bq9pqgcs.apps.googleusercontent.com',
    iosBundleId: 'dev.hamasur.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuz4yA4LOsa3ANHndAmgirF1d8QaJ2z6o',
    appId: '1:661690890987:web:e52d30598d09875c7d5cae',
    messagingSenderId: '661690890987',
    projectId: 'privateapp-hamasur',
    authDomain: 'privateapp-hamasur.firebaseapp.com',
    storageBucket: 'privateapp-hamasur.appspot.com',
    measurementId: 'G-P9NQWXX6L4',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDuz4yA4LOsa3ANHndAmgirF1d8QaJ2z6o',
    appId: '1:661690890987:web:a9e74499146355ea7d5cae',
    messagingSenderId: '661690890987',
    projectId: 'privateapp-hamasur',
    authDomain: 'privateapp-hamasur.firebaseapp.com',
    storageBucket: 'privateapp-hamasur.appspot.com',
    measurementId: 'G-L4YCR3NKMM',
  );
}
